/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/videos/resolve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * YouTube URL → 영상 ID
         * @description URL 에서 11자 영상 ID 를 뽑아 돌려준다. YouTube 영상 URL 이 아니면 422. 클라이언트는 이 값을 Supabase `videos` INSERT 에 쓴다.
         */
        post: operations["resolve_video_url_api_v1_videos_resolve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/videos/{video_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 영상 상태 (Phase 1-2 목 응답)
         * @description 현재는 고정된 더미 데이터. Phase 3-4 에서 실제 질의로 바꾼다.
         */
        get: operations["get_video_api_v1_videos__video_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/places": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 장소 목록 (Phase 1-2 목 응답)
         * @description 지도에 꽂을 장소를 커서 페이지네이션으로 돌려준다. 현재는 고정된 더미 데이터이며 `video_id` 필터만 흉내낸다.
         */
        get: operations["list_places_api_v1_places_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Page[PlaceRead] */
        Page_PlaceRead_: {
            /** Items */
            items: components["schemas"]["PlaceRead"][];
            /** Next Cursor */
            next_cursor?: string | null;
        };
        /**
         * PlaceRead
         * @description 지도 마커 하나.
         *
         *     `geom` 은 노출하지 않는다 — 클라이언트에 필요한 건 `(lat, lng)` 뿐이고, WKB 를
         *     흘리면 좌표 순서 해석이 클라이언트마다 갈린다.
         */
        PlaceRead: {
            /**
             * Name
             * @example 을지다방
             */
            name: string;
            /**
             * Category
             * @example cafe
             */
            category?: string | null;
            /** Address */
            address?: string | null;
            /** Google Place Id */
            google_place_id?: string | null;
            /** Lat */
            lat?: number | null;
            /** Lng */
            lng?: number | null;
            /**
             * Confidence
             * @default 0
             */
            confidence: number;
            /** @default video */
            source_modality: components["schemas"]["SourceModality"];
            /**
             * Context Start Sec
             * @example 132
             */
            context_start_sec: number;
            /**
             * Context End Sec
             * @example 148
             */
            context_end_sec: number;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Video Id
             * Format: uuid
             */
            video_id: string;
            /** Raw Extracted Text */
            raw_extracted_text: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * SourceModality
         * @description 장소 후보가 어느 신호에서 나왔는지.
         *
         *     A안(Gemini 단일 영상 입력)만 쓰는 지금은 전부 `VIDEO` 로 들어온다. B안(멀티모달
         *     앙상블)으로 갈 때 모달리티별 정확도를 **마이그레이션 없이** 비교하려고 지금부터
         *     컬럼을 둔다. `pipeline.types.PlaceCandidate.source_modality` 와 같은 값 집합이다.
         * @enum {string}
         */
        SourceModality: "audio" | "vision" | "text" | "video";
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * VideoCreate
         * @description 영상 등록 요청.
         *
         *     실제 INSERT 는 클라이언트가 Supabase 에 직접 한다(그 INSERT 가 Webhook 으로
         *     FastAPI 를 깨운다). 이 스키마는 그 전에 URL 을 검증하고 `youtube_id` 를
         *     뽑아 주는 쪽에서 쓴다 — 추출 규칙이 web·extension·API 세 곳에 흩어지지 않게
         *     OpenAPI 로 내보내 공유한다.
         */
        VideoCreate: {
            /**
             * Youtube Url
             * Format: uri
             */
            youtube_url: string;
            /**
             * Youtube Id
             * @default
             */
            youtube_id: string;
        };
        /**
         * VideoRead
         * @description 영상 한 편의 현재 상태.
         *
         *     `status` 를 Supabase Realtime 으로 구독하는 쪽이 보는 모양과 같다.
         *     `cost_usd` 는 넣지 않는다 — 비용 상한을 조정하기 위한 운영 지표이고 화면에 쓸
         *     곳이 없다. 민감한 값은 아니라 RLS 쪽에서는 SELECT 를 막지 않았다(막으면
         *     supabase-js 의 `select('*')` 가 전부 깨진다).
         */
        VideoRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Youtube Url */
            youtube_url: string;
            /** Youtube Id */
            youtube_id: string;
            /** Title */
            title?: string | null;
            /** Channel */
            channel?: string | null;
            /** Duration Sec */
            duration_sec?: number | null;
            /** Thumbnail Url */
            thumbnail_url?: string | null;
            status: components["schemas"]["VideoStatus"];
            /** Error Message */
            error_message?: string | null;
            /** Processed At */
            processed_at?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * VideoStatus
         * @description 영상 처리 파이프라인의 단계.
         *
         *     클라이언트는 Supabase Realtime 으로 이 값의 변화를 구독한다. 그래서 단계 이름이
         *     곧 사용자에게 보이는 진행 표시가 된다 — 내부 구현 단위가 아니라 "지금 무엇을
         *     기다리는지"가 드러나는 이름을 쓴다.
         * @enum {string}
         */
        VideoStatus: "pending" | "downloading" | "analyzing" | "resolving" | "completed" | "failed";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    resolve_video_url_api_v1_videos_resolve_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VideoCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VideoCreate"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_video_api_v1_videos__video_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                video_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VideoRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_places_api_v1_places_get: {
        parameters: {
            query?: {
                /** @description 이 영상의 장소만 */
                video_id?: string | null;
                limit?: number;
                /** @description 이전 응답의 next_cursor */
                cursor?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_PlaceRead_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
